### ISSUE TITLE
Support Flyway 5.x and Spring Boot 2.x

### ISSUE THREAD

**Issue by SingleShot** [zonkyio/embedded-database-spring-test#10]
We are currently upgrading to Spring Boot 2, which uses Flyway 5. It would be great if this tool could support Flyway 5 as well. My workaround of course is to stay on Flyway 4.2.0 but it would be nice to upgrade.

**Comment by tomix26** [comment]
Hi, what version of embedded database do you use? Because since version 1.3.0, Spring Boot 2 and Flyway 5 should be supported. Here is a [demo project](https://github.com/tomix26/embedded-database-demo) that uses them and works well.

**Comment by SingleShot** [comment]
I was on `1.2`. I looked in mvnrepository.com for the latest version and saw `1.2` is the latest for `embedded-database-spring-test-core` so figured that's the latest. After your question I played around a bit and now my tests are working great. 

I'm not sure if this is expected or not, but I have to list the following two dependencies or my tests won't run:
```
<dependency>
    <groupId>io.zonky.test</groupId>
    <artifactId>embedded-database-spring-test</artifactId>
    <version>1.3.0</version>
</dependency>

<dependency>
    <groupId>io.zonky.test</groupId>
    <artifactId>embedded-database-spring-test-core</artifactId>
    <version>1.2.0</version>
</dependency>
```

Omitting `embedded-database-spring-test-core` leads to this:
```
Caused by: java.lang.ClassNotFoundException: io.zonky.test.db.postgres.EmbeddedPostgresContextCustomizerFactory
```

But I'm good now. Thanks!

**Comment by SingleShot** [comment]
It's possible I am having some dependency issues with my Spring Boot 2 upgrade. I shall report back ;)

**Comment by tomix26** [comment]
The previous `embedded-database-spring-test-core` maven artifact was the same as `embedded-database-spring-test` artifact but with disabled auto-configuration. The same result is newly achieved by this:
```
<dependency>
    <groupId>io.zonky.test</groupId>
    <artifactId>embedded-database-spring-test</artifactId>
    <version>1.3.0</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>io.zonky.test</groupId>
            <artifactId>embedded-database-spring-test-autoconfigure</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
It is described in the documentation: https://github.com/zonkyio/embedded-database-spring-test#disabling-auto-configuration

So there is no need to use the `embedded-database-spring-test-core` artifact at all. And that's why Flyway 5 does not work for you. Because the stack trace you have attached is from the older `embedded-database-spring-test-core:1.2.0` artifact and not from the newer `embedded-database-spring-test:1.3.0` in which the support for Flyway 5 was added.

**Comment by tomix26** [comment]
The `ClassNotFoundException` is strange, because the class is definitely part of `embedded-database-spring-test:1.3.0` artifact. Try to clean up your local maven repository, maybe it will help.

**Comment by SingleShot** [comment]
Oops. Forgot to report back. My issues were indeed caused by transitive dependency messiness in my upgrade to Spring Boot. All is working, and in the manner documented in the project README. Please close this ticket as "Won't Fix: Reporter is an Idiot" 😛 

Thanks again for making this tool available and supporting it!

**Comment by tomix26** [comment]
Thanks for the feedback. I'm glad everything is working fine. 🙂
