### ISSUE TITLE
cannot be cast to javax.sql.DataSource

### ISSUE THREAD

**Issue by majoer** [zonkyio/embedded-database-spring-test#11]
Consider the following Spring configuration:
```
@Configuration
public class DatasourceConfiguration {

    @Bean(name="dataSource")
    public DataSource dataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean
    public CustomBean someOtherBeanThatDependsOnDataSource() {
        return new CustomBean(dataSource()); // <-- Invoking dataSource() here throws exception
    }
}
```
And the following Spring test:

```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = SpringEmbeddedPostgres.class)
@AutoConfigureEmbeddedDatabase
@FlywayTest
public class SpringEmbeddedPostgresTest {

    @Test
    public void should_start() {
        Assert.assertTrue(true);
    }
}
```

Which will result in this exception:
```
java.lang.ClassCastException: io.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean$$EnhancerBySpringCGLIB$$d97cbff cannot be cast to javax.sql.DataSource
```
Runnable example [here](https://github.com/majoer/spring-embedded-postgres)

**Comment by tomix26** [comment]
Thanks for the report and the test.

I investigated the problem and found out that it is probably a bug in Spring framework itself. The embedded database library uses a bean implementing `FactoryBean<DataSource>` interface for creating the data source bean and it looks like Spring framework is not able to evaluate factory bean properly when the direct calling of bean providing method is used.

But I found a workaround, try this:
```
@Bean
public CustomBean someOtherBeanThatDependsOnDataSource(DataSource dataSource) {
    return new CustomBean(dataSource);
}
```

Is this solution sufficient for you?

**Comment by tomix26** [comment]
It's possible that indirect autowiring is not so strict for the bean type as in the case of the direct calling of the method. Unfortunately, I'm not able to solve this problem easily because I use standard techniques of Spring framework for bean creation. It should work, but it does not work. So, can I close this issue?

**Comment by majoer** [comment]
yes, you may close. Keep up the good work :)

**Comment by tomix26** [comment]
I'm reopening this issue, because since Spring 5.0 it's possible to bypass the problem by using `AbstractBeanDefinition#setInstanceSupplier` method instead of the bean factory.
