### ISSUE TITLE
Handle manual query with embedded postgres 

### ISSUE THREAD

**Issue by Nihal-kansagra** [zonkyio/embedded-database-spring-test#111]
Hi there,

My need is that i need to write some manual queries, like opening an connection to database using URL,username,password and that is being fetched from properties file, now for test cases i need to run this manual queries on embedded database. Currently when i run test case it is fetching from original database and not from embedded database.

Is there a way to configure this?

**Comment by tomix26** [comment]
Hi, this is not how this library works. If you do not use an injected data source and open connections manually using url instead, then the library cannot work properly. You can use a lower-level api to initialize a postgres cluster on a specific port and manually create a new database with a specific name and other necessary attributes, but in that case, you will not use the full potential of this library.

There is an example:
```java
EmbeddedPostgres pg = EmbeddedPostgres.builder().setPort(5432).start();
JdbcTemplate template = new JdbcTemplate(pg.getPostgresDatabase());

template.execute("create database mydb");
template.execute("create user myuser with encrypted password 'mypass'");
template.execute("grant all privileges on database mydb to myuser");
```

After running the previous example, you will get a new database that will be available on a specific port, with a specific database name, and a specific username and password.

However, as I mentioned, I do not recommend this solution, instead I would suggest modifying the application to use the application data source.
