### ISSUE TITLE
Is is possible to run a init SQL script for the embedded database?

### ISSUE THREAD

**Issue by keith-miller** [zonkyio/embedded-database-spring-test#119]
Hello, first just wanted to say thanks for this library, it's really good. Now for my question: is it possible to run a SQL script on the embedded database before Flyway is run? The reason I ask is that we are using your tool for testing, but CockroachDB in our environments, so we need to install some extensions in the embedded Postgresql that we won't be running from Flyway normally. Thanks!

**Comment by keith-miller** [comment]
Of course after I posted I figured out that I could just overwrite the specific migration files and put them in `test/resources`. I still am curious about the question though.

**Comment by tomix26** [comment]
Hey, at this moment, the easiest option is to use the Flyway migrations as you mentioned. The second option is to use [docker provider](https://github.com/zonkyio/embedded-database-spring-test#using-docker-provider) and prepare a custom docker image that includes the extensions you need.

**Comment by keith-miller** [comment]
Great, thanks for the answer.
