### ISSUE TITLE
too much non-configurable debug output

### ISSUE THREAD

**Issue by 2019-05-10** [zonkyio/embedded-database-spring-test#123]
Basically each and every SQL statement is printed to stdout, prefixed with "Hibernate: ".
There seems to be no option to disable that output, instead it fills up the console and drowns relevant information.

**Comment by tomix26** [comment]
I don't think it has anything to do with the embedded postgres. Hibernate has its own logging configuration. Try something like this: `<property name="show_sql">false</property>` to disable it.

**Comment by 2019-05-10** [comment]
That I already did:
spring.jpa.show-sql=false
to no avail.

Turns out, I have additionally do
spring.jpa.properties.hibernate.show_sql=false

Since for Spring the first is sufficient, but embedded-database-spring-test does require yet another setting -- is it possible you somewhere skip the setting?
