### ISSUE TITLE
Flyway migrations run even when Flyway is not present

### ISSUE THREAD

**Issue by metsfan** [zonkyio/embedded-database-spring-test#133]
I do not use flyway in my application, but still when I run my tests, this plugin will attempt to load the Flyway bean. Is there a way around this issue?

**Comment by tomix26** [comment]
You have to add `spring.flyway.enabled=false` property to your application configuration. More info about this issue is here: https://github.com/zonkyio/embedded-database-spring-test/issues/76 Or you can wait for version 2.0.0, which should come out in a few days or weeks.

**Comment by metsfan** [comment]
Thank @tomix26 , I will try doing that.
