### ISSUE TITLE
Allow custom driver and jdbc property

### ISSUE THREAD

**Issue by elenoir** [zonkyio/embedded-database-spring-test#148]
Hi,

Thanks for your amazing work, really much appreciated.

A quick question regarding the possible usage of library such as p6Spy in addition to yours: to be able to print out every jdbc parameters, we have to be able to "inject" the p6Spy interceptor in the jdbc URL as follow:
`jdbc:p6spy:postgresql://`
And also set the Driver to 
`com.p6spy.engine.spy.P6SpyDriver`

Do you see an easy way to do it currently with the library?
I had a quick look into the sources and these parameters seem hardcoded and hard to override at some point...

**Comment by tomix26** [comment]
Hi, thanks for the question.

You can override a corresponding database provider and wrap the provided data source by `P6DataSource` before returning it to further processing. The database providers are not hardcoded and may be overridden as standard spring beans.

```java
@Bean
public DatabaseProvider zonkyPostgresProvider(Environment environment, ObjectProvider<List<Consumer<EmbeddedPostgres.Builder>>> databaseCustomizers) {
    return new ZonkyPostgresDatabaseProvider(environment, databaseCustomizers) {
        @Override
        public DataSource getDatabase(DatabasePreparer preparer) throws SQLException {
            DataSource database = super.getDatabase(preparer);
            return new P6DataSource(database);
        }
    };
}
```

In this example, I expect you use the default `ZonkyPostgresDatabaseProvider` provider. if not, the name of the bean you need to override may differ.

The names of other providers are available here: https://github.com/zonkyio/embedded-database-spring-test/blob/master/embedded-database-spring-test/src/main/java/io/zonky/test/db/postgres/EmbeddedPostgresContextCustomizerFactory.java#L213

**Comment by ifs-eriklenoir** [comment]
It works like a charm, appreciate.

**Comment by elenoir** [comment]
It works like a charm, appreciate.
