### ISSUE TITLE
Create Schema and change to Default

### ISSUE THREAD

**Issue by Mom0aut** [zonkyio/embedded-database-spring-test#157]
Hello,

i need to change the default schema and create in the schema new tables.
I cant currently use flyway thats my main problem.

The current scripts are creating the tables at the wrong database/schema.

Can i specifiy which databases/schemas are created with the embedded Posgres Server?

Screenshot from the desired behavior:
![DefaultSchema](https://user-images.githubusercontent.com/30840092/112189966-d8345c00-8c04-11eb-92ee-31b9650e9a9c.png)

Regards Mom0

**Comment by Mom0aut** [comment]
i changed the user with default search path this fixed my issue

**Comment by tomix26** [comment]
Hi, the embedded database does not affect that. It depends on the database migration tool, such as Flyway or Liquibase. If you are using some manual scripts, you have to write sql statements containing the full name of a target resource, including the schema name.
