### ISSUE TITLE
Ability to set up outside of tests

### ISSUE THREAD

**Issue by jeremysule** [zonkyio/embedded-database-spring-test#160]
Hi -Can we start an embedded db outside of spring tests? I'd like to set up the app in "local" mode, where everything is in memory. This works great for tests.

**Comment by tomix26** [comment]
Hi, if you mean using an embedded database to run a regular application, it is not possible and probably won't be in the future. For these cases, I would rather recommend using docker, which allows you to keep data between multiple runs of the application.

**Comment by tomix26** [comment]
No response, I'm closing the issue.
