### ISSUE TITLE
`zonky.test.database.replace=none` does not work as expected

### ISSUE THREAD

**Issue by tomix26** [zonkyio/embedded-database-spring-test#163]
Originally reported by @nbabb:

> I have tried using the above property, either from the command line or via application.yaml (in a spring boot application), and am not getting quite the expected behavior.  What we want is for the embedded db to be used only in certain cases, and by default we want to use an actual db.
> 
> So we have spring setup with a datasource
> ```
> spring:
>   datasource:
>     url: ${JDBC_URL}
>     username: ${JDBC_USERNAME}
>     password: ${JDBC_PASSWORD}
> ```
> and then our test class is annotated with `@AutoConfigureEmbeddedDatabase(provider = ZONKY, type = POSTGRES)`
> 
> With the property set to `NONE`
> ```
> zonky:
>   test:
>     database:
>       replace: NONE
> ```      
>   
> I end up with errors in spring
> ```
> Caused by: org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
> 	at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:34)
> 	at org.flywaydb.core.Flyway.execute(Flyway.java:416)
> 	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
> 	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet
> ```
> where if I simply comment out the `@AutoConfigureEmbeddedDatabase` annotation the test runs fine.  I do see the log message set `The use of the embedded database has been disabled` when I set to NONE.
> 
> Any thoughts on this (or alternatives to consider)?  Thanks.
> 
> UPDATE: I think the issue is that, because the annotation is on the test class, then EmbeddedDatabaseContextCustomizer takes effect, even though the property is set to NONE.  If the property is set to NONE, it seems like the `@AutoConfigureEmbeddedDatabase` should have no effect.
> 
> I'm guessing that if `EmbeddedDatabaseContextCustomizerFactory.createContextCustomizer` where to return null, in response to the property being NONE, then this would resolve my issue.
> 
> I did come across this section https://github.com/zonkyio/embedded-database-spring-test#disabling-auto-configuration of the documentation.  This might be an option for me, i.e. disable auto config, and then I can conditionally configure, based on properties.  I'm not sure I'd know how to configure things manually however.  
> 
> Any insight @tomix26 into this issue is appreciated.

**Comment by nbabb** [comment]
Hi @tomix26 so I tried the new 2.0.1 build for `embedded-database-spring-test`.  In application.yaml I have

```
zonky:
  test:
    database:
      replace: none
```
and this seems to disable zonky.  However, in our deployed environment I am trying to re-enable by passing `-Dzonky.test.database.replace=any` to the gradle build task.  I see in the logs this message

`The use of the embedded database has been disabled` so the override doesn't appear to be working.  Any thoughts on this?  Thanks

**Comment by tomix26** [comment]
How do you pass the parameters? Using the `jvmArgs` option in test task? Because I just tried it and it worked as expected.

Here is example of my configuration:
```
test {
   jvmArgs '-Dzonky.test.database.replace=any'
 }
```
