### ISSUE TITLE
Not able to use @FlywayTest

### ISSUE THREAD

**Issue by pabloedm** [zonkyio/embedded-database-spring-test#172]
Hey there,

I updated the spring-boot version to 2.6.0, but then my tests with Junit4 started to fail. So now Im using JUnit Jupiter and JUnit vintage to maintain compatibility along with JUnit4 tests.
The problem Im facing right now is that Im not being able to use the annotations `@FlywayTest` along with embedded-database-spring-test.
I've configured my pom as

		<dependency>
			<groupId>org.flywaydb.flyway-test-extensions</groupId>
			<artifactId>flyway-spring-test</artifactId>
			<version>7.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.zonky.test</groupId>
			<artifactId>embedded-database-spring-test</artifactId>
			<version>2.0.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.zonky.test.postgres</groupId>
			<artifactId>embedded-postgres-binaries-linux-amd64</artifactId>
			<version>13.2.0</version>
			<scope>test</scope>
		</dependency>

My test class is configured as follow:

```
  @RunWith(SpringRunner.class)
  @SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
  @AutoConfigureEmbeddedDatabase
  @TestExecutionListeners({ DependencyInjectionTestExecutionListener.class,
          FlywayTestExecutionListener.class })
  public class TestEnvironment {
```

And I have a before method configuring the `@FlywayTest` annotation:

```
    @Before
    @FlywayTest(locationsForMigrate = { "classpath:/db/migration", "classpath:/db/testdata" })
    public void before() {
    }

```

So when running my tests, the following error occurs:

```
java.lang.IllegalStateException: Using org.flywaydb.test.FlywayTestExecutionListener and org.flywaydb.test.junit.FlywayTestExecutionListener is forbidden, use io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener instead
```

I tried to change the `FlywayTestExecutionListener` to `OptimizedFlywayTestExecutionListener` and then I got the error:

```
 java.lang.IllegalArgumentException: Could not find constructor on class org.flywaydb.core.internal.scanner.Scanner
	at io.zonky.test.db.util.ReflectionUtils.invokeConstructor(ReflectionUtils.java:124) ~[embedded-database-spring-test-2.0.1.jar:na]
	at io.zonky.test.db.util.ReflectionUtils.invokeConstructor(ReflectionUtils.java:104) ~[embedded-database-spring-test-2.0.1.jar:na] 
```

what am I doing wrong here? 
I had all this working fine in previous libs and spring-boot versions.

thanks in advance.

**Comment by tomix26** [comment]
Hi, thanks for the report. You're right, since Flyway 7.9.0 there is some internal incompatibility. I'll take a look at it and try to fix it as soon as possible.
