### ISSUE TITLE
Set connection parameter stringtype=unspecified

### ISSUE THREAD

**Issue by denizengin87** [zonkyio/embedded-database-spring-test#18]
Hi,

this is an issue, only if there is no way to achieve what is explained hereinafter. Sorry if this is not the right place to ask, but I didn't know where else to ask.  
In my project I use spring data jpa together with a postgres database. In that project I store Java Strings in a jsonb column of the postgres db. This is possible via setting the postgres connection parameter stringtype to the value unspecified. I did this in my spring configuration yaml and everything works fine in combination with my real non-embedded postgres db. But the configuration parameters aren't used when I use your emdedded postgres for integration testing. Is there a way to inject this connection property? I tried some stuff, but yet didn't find the right place.

Thx in advance!

**Comment by tomix26** [comment]
Normally this would be configured in this way:
```
@Bean
public Consumer<EmbeddedPostgres.Builder> embeddedPostgresCustomizer() {
    return builder -> builder.setConnectConfig("stringtype", "unspecified");
}
```
But there is a bug in implementation of [otj-pg-embedded](https://github.com/opentable/otj-pg-embedded) library on which we depend. So it does not work as it should. The connection parameters are used only when a database is starting, but not to connect to a running database.

I already have some open pull requests to that project, but nothing has been happening for a long time. So I plan to fork the project and then I'll be able to fix this issue.

**Comment by denizengin87** [comment]
Hi,

thx for the answer. So, using EmbeddedPostgres.Builder.setConnectConfig() was the right way to do it.
Could you estimate when milestone 1.3.3 will be released? Sounds like a bigger change, which I can't await :)
Shortly, I was able to work around the problem by using a second flyway sql file for my tests, in which I declared the type of the column as a varchar, but now I want to add functionality to my query using the jsonb operator @>  , that's why I can't use the workaround any longer.

**Comment by tomix26** [comment]
I estimate that it could be finished in a week or two. Unfortunately there is no simple workaround for this issue.
