### ISSUE TITLE
Init scripit 

### ISSUE THREAD

**Issue by komaroffdd** [zonkyio/embedded-database-spring-test#187]
Hello!

I have a question, how to execute init script(_example_ **CREATE DATABASE; CREATE some_user;**) before migrations;

**Suite**
Migrations are rolled under users in the database, so before migrations we need to roll the init script.
Thanks!

- Java 11
- Spring boot 2.5.5
- Postgres 11
- Junit5
- Liquibase

**Comment by tomix26** [comment]
Hi, I think that it should be possible to prepare a special test liquibase changelog to include the main changelog and also some additional testing migrations/operations. Check out this page: https://docs.liquibase.com/concepts/advanced/include.html

If this solution is not suitable for you, you can also use [ResourceDatabasePopulator](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/init/ResourceDatabasePopulator.html) to initialize the database manually, and register it using [DatabaseInitializerDetector](https://docs.spring.io/spring-boot/docs/2.5.2/api/org/springframework/boot/sql/init/dependency/DatabaseInitializerDetector.html) or [BeanPostProcessor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/config/BeanPostProcessor.html).

**Comment by komaroffdd** [comment]
Hello thanks! I will try both options and return to this thread with some solution
