### ISSUE TITLE
Suggestion: IntelliJ automatic DB connection

### ISSUE THREAD

**Issue by Hollerweger** [zonkyio/embedded-database-spring-test#193]
HI,

When running a test i can see the connection URL printed to the log and can manually connect in IntelliJ to this db.

```
i.z.t.d.l.EmbeddedDatabaseReporter: JDBC URL to connect to 'dataSource':
url='jdbc:sqlserver://localhost:49154;databaseName=cywlsplkqkij;user=sa;password=A_Str0ng_Required_Password', scope='ClientControllerTests#createClientsTest'
```
Is there a way that IntelliJ can automatically connect to this db?
IntelliJ supports also "Data Source from Path" so maybe this plugin could write the connection settings to a defined file path where IntellJ could read it.

This would be quite useful for debugging to avoid searching the connection URL in the logs and updating the config for every test run.

We are using Postgres and MSSQL Server.

**Comment by rkrisztian** [comment]
So far I've been doing this:

* Add to your test code:
  ```java
  @Autowired
  DataSource dataSource;
  ```
* Add a breakpoint to the test code, and run the test in debug mode.
* _Evaluate Expression_ → `dataSource.unwrap(EmbeddedDatabase.class).getJdbcUrl()`, and copy its value to the clipboard. (You can import classes there.)
* Press Shift twice, type in Database, and press Enter.
* Add Data Source from URL, paste the URL, and select the PostgreSQL driver.
* Test the connection, download the driver if missing.

But to keep the same database between test runs, [we need more configuration](https://github.com/zonkyio/embedded-database-spring-test/issues/185), which I haven't elaborated yet...

This is of course still a bit cumbersome, I wish there was something easier.

**Comment by tomix26** [comment]
@rkrisztian You don't have to evaluate expressions on the embedded data source to obtain the connection url. The intended and much easier way is to copy it from logs, as @Hollerweger wrote.

@Hollerweger I don't know of any better way at the moment. What is important to note is that the database name may differ for each run or each test execution. So the "Data Source from Path" option would probably not be useful in that case. However, even though I understand that it could be better if the whole solution was automated, I don't find the current process to be too complicated. You just need to copy the link from the log and use the "Data Source from URL" option in IntelliJ. All the necessary data is already included in the link.

**Comment by krisztian-romek** [comment]
Thanks, @tomix26 , I didn't notice that in the documentation, my bad.

**Comment by rkrisztian** [comment]
Thanks, @tomix26 , I didn't notice that in the documentation, my bad.

**Comment by tomix26** [comment]
As I already wrote, I have no idea how to make this process faster and more convenient. So for now I'm closing the issue, feel free to reopen it if you get any ideas.
