### ISSUE TITLE
Database Initialization issues, can't find postgres binary

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [zonkyio/embedded-database-spring-test#213]
Hello,

First of all, thank you for having these open source solutions. They're excellent and quite helpful. I am trying to get my current project to work on a Mac M1, and was able to solve most issues. The one I'm currently facing involves `embedded-database-spring-test`. 

The current version that is being used is `io.zonky.test:embedded-database-spring-test:1.6.3`, and we would like to upgrade in the near future, but `2.x` introduces breaking changes that we'd have to solve (and are somewhat absent from the upgrade guide?). Anyway, as I am sitting on arm64 platform, I upgraded `io.zonky.test.postgres:embedded-postgres-binaries-bom`to `15:0.0`, which according to the gradle log, and my console output, downloads all the possible binaries:

```
embedded-postgres-binaries-bom
embedded-postgres-binaries-darwin-amd64
embedded-postgres-binaries-darwin-arm64v8
embedded-postgres-binaries-linux-amd64
embedded-postgres-binaries-linux-amd64-alpine
embedded-postgres-binaries-windows-amd64
```

Now, whenever I start running my tests, they fail. To be precise, they fail using an `initializationError`, which is cause by it not finding the correct binary:

```
2022-10-27T13:37:10,184 ERROR [    Test worker] [.DefaultPostgresBinaryResolver] No postgres binaries were found, you must add an appropriate maven dependency that meets the following parameters - system: Darwin, architecture: arm_64
2022-10-27T13:37:10,201 ERROR [    Test worker] [ice.RsmFlywayDataSourceContext] Failed to set up test DB
```

_I assume it might be because it's looking for `darwin-arm64`_ but it can only find `darwin-arm64v8`, but can't confirm it_

Any way, this of course leads to it failing and therefor not passing. What I can say is that on a linux OS machine, the project can test without any issue using `io.zonky.test.postgres:embedded-postgres-binaries-bom:11.9.0`.

So I assumed that this might be an issue involving macOS - according to my research, gradle cached files are saved on the same spot as they would be under linux, so that shouldn't be the issue. (I don't even know where it tries to find the binaries, so theres that).

**Comment by SergeyAblaev** [comment]
I have some problems too! I think that needed move test configuration from embedded postgres to docker tests for mac M1

**Comment by RicardoMonteiroSimoes** [comment]
The issues seems to be that some older zonkyio (anything pre 2) cannot correctly get the naming of the binaries, but I might be wrong.

**Comment by tomix26** [comment]
Hi @RicardoMonteiroSimoes.

The naming conventions of the binaries haven't changed since the beginning of the project, so that's not the problem. The `system: Darwin, architecture: arm_64` parameters are also correct.

The most likely cause of the problem are missing binaries. The dependency containing ARM binaries is not included by default, it must be added explicitly. Specifying a BOM file is not enough, it is only for managing the same versions.

So are you sure you added this dependency correctly? What type of dependency management system are you using? Maven, Gradle or something else? Can you attach an example?

Here are more details about enabling additional architectures: https://github.com/zonkyio/embedded-postgres#additional-architectures

**Comment by tomix26** [comment]
What issues have you faced during the upgrade that are not described in the upgrade guide?
https://github.com/zonkyio/embedded-database-spring-test/wiki/Embedded-Database-2.0-Release-Notes#upgrading-from-embedded-database-1x

**Comment by RicardoMonteiroSimoes** [comment]
> The most likely cause of the problem are missing binaries. The dependency containing ARM binaries is not included by default, it must be added explicitly. Specifying a BOM file is not enough, it is only for managing the same versions.

Ah, that was the mistake. Was under the impression that the `BOM` included all Binaries, which is only the case for AMD64. After adding the `ARM` one the error went away.

> What issues have you faced during the upgrade that are not described in the upgrade guide?

Up until now I extended the `DefaultFlywayDataSourceContext`, which of course is gone with v2+. It's replacement isn't quite clear to me - there are mentions of classes being moved/refactored, but that's about it.

**Comment by tomix26** [comment]
> Right now, even after clearing the var/folders/... temporary data, it fails to initialize the database.

Could you please attach the log file for further investigation?

> Up until now I extended the DefaultFlywayDataSourceContext, which of course is gone with v2+. It's replacement isn't quite clear to me - there are mentions of classes being moved/refactored, but that's about it.

This is a low level internal API, so I didn't expect that anyone would need to extend this class. But if you think it might be useful, feel free to open a separate issue for that.

**Comment by tomix26** [comment]
Or just join this one #216

**Comment by RicardoMonteiroSimoes** [comment]
> Or just join this one #216

Yup, that one is basically the same.
