### ISSUE TITLE
ignoreMissingMigrations 

### ISSUE THREAD

**Issue by codex70** [zonkyio/embedded-database-spring-test#218]
Latest version of flyway fails as method ignoreMissingMigrations no longer exists.

See: https://stackoverflow.com/questions/73068931/how-to-upgrade-from-flyway-5-2-4-to-9-0-1

**Comment by tomix26** [comment]
The fix is already prepared but hasn't been released yet. The related issue: https://github.com/zonkyio/embedded-database-spring-test/issues/207

**Comment by codex70** [comment]
Thanks for letting me know, is there any idea of when this will be released, or do you know of a workaround until release?

**Comment by tomix26** [comment]
Actually, I don't know about any workaround, but I'll try to release the new version as soon as I possible.
