### ISSUE TITLE
Does Zonkyio docker provider allow for custom entry command?

### ISSUE THREAD

**Issue by hardcoresummer** [zonkyio/embedded-database-spring-test#237]
As the title said. Currently it seems like the entry command for docker provided (at least in Postgresql Container) is always hardcoded to `postgresql -c FSYNC_OFF_OPTION` . It would be very helpful if we can customize the command instead of this, like for debugging purpose when i want to run 'postgresql -c log_statement=true' but it get overridden by zonkyio.
Is there any attempt to make, or consider this feature at the moment?

**Comment by tomix26** [comment]
You can use the following configuration property:
`zonky.test.database.postgres.server.properties.log_statement=all`

**Comment by tomix26** [comment]
There is more info about it here: https://github.com/zonkyio/embedded-database-spring-test#postgresql-configuration

**Comment by hardcoresummer** [comment]
Understood, many thanks to you!
