### ISSUE TITLE
[Q]: Is there a way to use the latest testcontainer version

### ISSUE THREAD

**Issue by kuza2010** [zonkyio/embedded-database-spring-test#244]
Current project dependency is: 
> - [Spring Framework](https://spring.io/) (5.3.24) - spring-test, spring-context modules
> - [Testcontainers](https://www.testcontainers.org/) (1.17.6)
> - [Cedarsoftware](https://github.com/jdereg/java-util) (1.68.0)
> - [Guava](https://github.com/google/guava) (23.0)

For now there is a nre test container version (1.18.3) available. Can we somehow instruct `embedded-database-spring-test
` use that?

**Comment by tomix26** [comment]
Yes, sure, there is a way. But the way how to do that really depends on a type of dependency management system you are using. For example, in case of Maven you can use the dependency management section to override a version of any transitive dependency. In case of Grade, it should be enough just explicitly define the dependency in the build script and the newest version in the dependency tree wins.

**Comment by kuza2010** [comment]
Ok, thanks, that is clear!
