### ISSUE TITLE
All data providers being required when only a specific one is specified 

### ISSUE THREAD

**Issue by dwi-mfbcs** [zonkyio/embedded-database-spring-test#252]
I’m experiencing problem with running unit tests that involve spinning up an embedded database (postgres). 

In this case, I specifies that I want to use specific provider (ZONKY).

```
@AutoConfigureEmbeddedDatabase(type = AutoConfigureEmbeddedDatabase.DatabaseType.POSTGRES, provider = ZONKY)
public class BaseComponentTest {
....
}
```

However it seems that it asks for all data providers being instantiated.

Example of error (in this case it asks for the `opentable` provider that I don’t ask):
```
Caused by: io.zonky.test.db.config.MissingProviderDependencyException: You have to add the following dependency to your project: 'com.opentable.components:otj-pg-embedded' (https://mvnrepository.com/artifact/com.opentable.components/otj-pg-embedded)
```

Version of libraries being used:

```
springframework 3.1.5
io.zonky.test:embedded-postgres:2.0.4
io.zonky.test:embedded-database-spring-test:2.3.0
io.zonky.test.postgres:embedded-postgres-binaries-bom:14.10.0
```

Am I missing something here? Looking for help with resolving this issue..

**Comment by tomix26** [comment]
Please try the following steps:
- upgrade to the latest version (2.4.0)
- ensure no providers are directly autowired
- confirm your spring context is set for lazy initialization (enabled by default)
  - see more at: https://springhow.com/lazy-initialization-in-spring-boot/

**Comment by dwi-mfbcs** [comment]
Thanks @tomix26 - I have ensured the settings that you suggested. I even explicitly set the lazy initialization to true. Unfortunately, still experiencing the same issue. 
Is there any debugging that you can suggest?

**Comment by dwi-mfbcs** [comment]
Thank you @tomix26 - it turns out it's a subtle mistake on my part. I was referencing an internal library with a wrong version (0.0.1.13 instead of 0.1.13, duh..). 
My apology for causing trouble here.
