### ISSUE TITLE
Use two different datasource

### ISSUE THREAD

**Issue by ErwanLeroux** [zonkyio/embedded-database-spring-test#33]
I'm currently developing an API that use two datasource, each pointing to a different schema of the database, using Spring Boot 2.0.3, Hibernate 5.2.17 and Flyway 5.2.0

```
@Primary
@Bean(name = "ds1")
@ConfigurationProperties(prefix = "spring.datasource")
public DataSource dataSource() {
    return DataSourceBuilder.create().build();
}

spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/db?currentSchema=sch1
spring.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.driver-class-name=org.postgresql.Driver

@Bean(name = "ds2")
@ConfigurationProperties(prefix = "ds2.datasource")
public DataSource dataSource() {
    return DataSourceBuilder.create().build();
}

ds2.datasource.jdbc-url=jdbc:postgresql://localhost:5432/db?currentSchema=sch2
ds2.datasource.username=${spring.datasource.username}
ds2.datasource.password=${spring.datasource.password}
ds2.datasource.driver-class-name=${spring.datasource.driver-class-name}
```
In the tests, we are using two h2 datasource but we are confronted to more and more problems with the flyway migrations designed for postgres and not working in h2 (the last case was renaming a column).

I would like to switch to an embedded postgres for testing, but i can't find a way to make it work using two datasource, as AutoConfigureEmbeddedDatabase accept only one bean name and can't be set twice on a class.

How can I do that ?

**Comment by tomix26** [comment]
Now this is not possible, but it's a good tip for improvement. The `@AutoConfigureEmbeddedDatabase` annotation could be repeatable and then it should be possible to configure two different independent datasources.

Anyway, although the change may seem simple, it will be quite difficult to realize it. So I can't promise when, if at all, the change will be implemented.

**Comment by ErwanLeroux** [comment]
Thank you for the quick response.
Could it be done with a list of beanName instead of duplicating the annotation ?

**Comment by tomix26** [comment]
I think using repeatable annotation is more flexible than using a list of bean names. You can have a different configuration for each datasource. For instance, in the future, it will be possible to use a different database type for each datasource. The implementation complexity is the same for both solutions.

**Comment by ErwanLeroux** [comment]
You're right. 

> I think using repeatable annotation is more flexible than using a list of bean names. You can have a different configuration for each datasource. For instance, in the future, it will be possible to use a different database type for each datasource. The implementation complexity is the same for both solutions.

You're right
