### ISSUE TITLE
Tests should run on a clean database, each time!

### ISSUE THREAD

**Issue by rfftrifork** [zonkyio/embedded-database-spring-test#34]
**Steps to reproduce**
Write a few tests that modifies the content of the database, or have a BeforeEach that inserts data. Do not write any manual cleanup scripts (those should not be needed, they should be default).

**What happens**
The state leaks from the tests influencing other tests

**What I expected**
The database is cleared and re-initialized after each test

**Reason**
Testing 101, all tests should be independent, thus database state must never! leak between tests.

**Comment by tomix26** [comment]
It's easy, just place `@FlywayTest` annotation on your test class or test method. The `@FlywayTest` 
 annotation has set `invokeCleanDB` and `invokeMigrateDB` attributes to true by default, so it will refresh the database. Moreover, the embedded-database-spring-test library can optimize the database refresh, so this operation should be relatively fast and efficient. The database templates are used for this purpose.

In the future, I plan to extend the `@AutoConfigureEmbeddedDatabase` annotation by a refreshMode attribute, so it will be possible to use it as follows: `@AutoConfigureEmbeddedDatabase(refreshMode = RefreshMode.AFTER_EACH_TEST_METHOD)`. It will also be possible to place this annotation on an abstract test class or use it in a composed annotation to apply this behavior to all tests.

**Comment by rfftrifork** [comment]
Curious, we do have that annotation there, doesn't seem to be working then :/ But, I'm happy that you're planning those features :+1:

**Comment by tomix26** [comment]
If you want to isolate all tests, you need to put the `@FlywayTest` annotation on each test method separately. If you put this annotation only on a test class, all tests within that class share the same database. This can be useful for read only tests. Let me know if it solved your problem.

**Comment by tomix26** [comment]
I've mentioned it in the documentation., so I'm closing the issue.
