### ISSUE TITLE
How do use specific PostgreSQL binary in gradle

### ISSUE THREAD

**Issue by Siegrift** [zonkyio/embedded-database-spring-test#35]
I can see in the documentation for maven, how to pick a different PostrgeSQL binary, however there I am missing a description how to do it in gradle.

Lets say I want to use version 9.6. I tried following gradle dependencies:
```
testCompile "io.zonky.test:embedded-database-spring-test:1.3.4"
compile "io.zonky.test.postgres:embedded-postgres-binaries-bom:9.6.10"
```
However, I still see version 10.6 in tests. Can you tell me what am I doing wrong? (I assume, that after adding the binary dependency, there is no further configuration required)

**Comment by Siegrift** [comment]
I didn't try the first approach and unfortunately I am using gradle 4.9.

However the third approach works :) :+1:
Thanks for your help :)

**Comment by tomix26** [comment]
Glad to hear that, thanks for the info.

**Comment by drej1** [comment]
Hi @tomix26, I tried solution 1 and 3 but I get both 9.6.9 and 10.7.0 bineries into my dependencies in gradle and if I debug DefaultPostgresBinaryResolver it retrieved the 10.7.0 binary.
Could you please help?
I am using Gradle 4.10.

**Comment by tomix26** [comment]
Hi @drej1, could you please provide your `build.gradle` script?

**Comment by drej1** [comment]
Hi,

It's a multimodule project but I will try to add the relevant gradle files here:
root project: root_build.gradle
it includes: common.gradle
and there is a submodule which is dependency for other submodules: submodule_build.gradle
[gradle_files.zip](https://github.com/zonkyio/embedded-database-spring-test/files/3276174/gradle_files.zip)

**Comment by drej1** [comment]
Hi @tomix26 any update for this? Thx

**Comment by tomix26** [comment]
I'm so sorry for the late response, this task is already closed, so I forgot about our previous conversation. I think the problem could be caused by the fact that you apply the plugin only to submodules. Try to move it directly into the `root_build.gradle` script and don't use the `apply false` syntax for this plugin.

Something like this:
```groovy
buildscript {

    ext {
        // START for common.gradle
        swaggerCodegenVersion = "2.2.3"
        swaggerAnnotationsVersion = "1.5.21"
        springfoxSwaggerVersion = "2.9.2"
        mapstructMapperVersion = "1.3.0.Final"
        redissonVersion = "3.10.7"
        // END for common.gradle
    }

    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven { url "http://repo.spring.io/plugins-release" }
        maven {
            url "http://nexus.services.itc.st.sk:8081/repository/maven-central/"
            credentials {
                username "service-hal"
                password "XXX"
            }
        }
    }

    dependencies {
        // START for common.gradle
        classpath("io.spring.gradle:propdeps-plugin:0.0.9.RELEASE") // provides additional optional and provided dependency configurations
        classpath("io.swagger:swagger-codegen:${swaggerCodegenVersion}")
        // END for common.gradle
    }

}

plugins {
    id "io.spring.dependency-management" version "1.0.6.RELEASE"

    // spring boot
    id "org.springframework.boot" version "2.1.5.RELEASE" apply false

    // lombok
    id "io.franzbecker.gradle-lombok" version "3.0.0" apply false

    // for annotation processors | gradle 5 should have native support for annotation processors, so this plugin might be removed from the project after gradle upgrade
    id "net.ltgt.apt" version "0.21" apply false
    id "net.ltgt.apt-idea" version "0.21" apply false

    // flyway gradle plugin
    // please keep this version in sync with spring boot defined ${flyway.version}
    // https://github.com/spring-projects/spring-boot/blob/v2.1.5.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml
    id "org.flywaydb.flyway" version "5.2.4" apply false

    // sonarqube
    id "org.sonarqube" version "2.7.1" apply false
}

dependencyManagement {
     imports {
          mavenBom 'io.zonky.test.postgres:embedded-postgres-binaries-bom:9.6.10'
     }
}

group "sk.telekom.oneapp.hal"
version "1.0-SNAPSHOT"

apply from:"./gradle-common/common.gradle"
```

**Comment by drej1** [comment]
Hi @tomix26 , it didn't help, but I made some changes... I had to add 
{code}
dependencyManagement {
     imports {
          mavenBom 'io.zonky.test.postgres:embedded-postgres-binaries-bom:9.6.10'
     }
}
{code}
into the common.gradle into the subprojects {} closure... this way it was set in all subprojects using your library.

Thanks :)
