### ISSUE TITLE
Liquibase support

### ISSUE THREAD

**Issue by glockbender** [zonkyio/embedded-database-spring-test#46]
Do you plan to support Liquibase? Unfortunately flyway does not support Postgres 11

**Comment by tomix26** [comment]
Yes, it is on the roadmap, but not in the near future. It will be implemented in version 2.0 that is planned to be released in the next few months. So I'm afraid Postgres 11 will be supported by Flyway before completing this task.

However, the basic support for Liquibase should be already included. In case there is no Flyway bean in the spring context, an empty database is created and this database can be initialized by any tool, including Liquibase. The only missing feature is the ability to revert the database to its default state, before running the tests.

Is this expectation correct? Or do you have any other problems?

**Comment by glockbender** [comment]
Yes. Thanks a lot for a complete explanation.

**Comment by jmchuster** [comment]
> If you use Spring Boot framework, it is necessary to add `spring.flyway.enabled=false` property to your application configuration to disable `FlywayAutoConfiguration` and prevent automatic creation of a Flyway bean.

I'm glad I found this easily by searching the issues, but this should really also be in the documentation
