### ISSUE TITLE
How could i set a schema in the test?

### ISSUE THREAD

**Issue by arthurrio** [zonkyio/embedded-database-spring-test#48]
When the class EmbeddedPostgres create the jdbc url, the parameter are defined in the static string

``private static final String JDBC_FORMAT = "jdbc:postgresql://localhost:%s/%s?user=%s";``

How could I add the **currentSchema** ? 
Can I open a PR with the changes?

**Comment by arthurrio** [comment]
I found a way to set
```
@Configuration
class EmbeddedPostgresConfiguration {
    @Bean
    fun embeddedPostgresCustomizer(): Consumer<EmbeddedPostgres.Builder> {
        return Consumer { builder -> builder.setConnectConfig("currentSchema", "schema_name") }
    }
}
```

**Comment by tomix26** [comment]
You can set it easily through `zonky.test.database.postgres.client.properties.currentSchema=xxx` property.
More information about general configuration is described at https://github.com/zonkyio/embedded-database-spring-test#common-configuration
