### ISSUE TITLE
Using embedded Postgresl Database it in end-to-end tests

### ISSUE THREAD

**Issue by kicktipp** [zonkyio/embedded-database-spring-test#49]
I use your lib for integration test in my backend project. It runs just fine.
I have a Javascript frontend and now I want to run some end-to-end tests. For this my backend project gets packaged and startet with the Spring Boot maven plugin:
```

    <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <executable>true</executable>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <skip>${skipTests}</skip>
                            <profiles>
                                <profile>integration</profile>
                            </profiles>
                        </configuration>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <skip>${skipTests}</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
After my spring-boot backend was started a plugin runs npm tests with Cypress and Chromium against the running backend. 
``` 
   <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>${frontend-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>run e2e tests</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <workingDirectory>../frontend</workingDirectory>
                            <arguments>run verify</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

At the moment it uses a pre-configured test database on my developer machine. Everywhere I want to run the end-to-end tests I need to setup a postgresql Database.

I tried to move your lib from scope=test to scope=compile and just add a configuration like this to my main package:

```
@Configuration
@Profile("integration")
@AutoConfigureEmbeddedDatabase
public class PostgresqlIntegrationDatabase {}
```
This does not work as the @AutoConfigureEmbeddedDatabase annotation only works with a test class and in a test environment. This configuration just does nothing.

It would be nice to package this lib into the full-fledged JAR and have an embedded database with profile=integration.

This way we can use the same technique for integration and end-to-end testing. Otherwise we need to have a DockerContainer or Postgresql Database running on the machine.

**Comment by tomix26** [comment]
Interesting scenario, nevertheless the library is intended for testing-only purposes and it should never be part of production code, so using it in compile scope is not recommended. I think the use of a docker container is the ideal choice for this use. Because you can prepare a docker image containing test data and other necessary stuff.

The main advantage of this library is the efficient creation of isolated databases and the ability to change migration scripts for each test independently. But that is not something you need for running end-to-end tests. However, if you really can't use Docker for some reason, you can try to use lower-level api to create an empty embedded database.

Something like this:
```java
@Configuration
@Profile("integration")
public class PostgresqlIntegrationDatabase {

    @Bean
    public DataSource dataSource() {
        EmbeddedPostgres postgres = EmbeddedPostgres.start();
        return postgres.getPostgresDatabase();
    }
}
```

**Comment by tomix26** [comment]
Is this solution acceptable to you?

**Comment by kicktipp** [comment]
I decided to use a docker container.

Regards
Janning



Am 12. Mai 2019 13:09:17 schrieb Tomáš Vaněk <notifications@github.com>:

**Comment by tomix26** [comment]
Ok, thanks for the info, I'm closing the issue.
