### ISSUE TITLE
Breaks on Flyway 5.0+

### ISSUE THREAD

**Issue by maxkramerbcgdv** [zonkyio/embedded-database-spring-test#5]
We just upgraded to Spring 2.X and are having an issue using this with the latest version of Flyway. It errors out when creating the flywayInitializer bean:

> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> Caused by: java.lang.NoSuchMethodError: org.flywaydb.core.Flyway.isAllowMixedMigrations()Z
> 	at io.zonky.test.db.flyway.FlywayConfigSnapshot.<init>(FlywayConfigSnapshot.java:118)
> 	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.createConfigSnapshot(DefaultFlywayDataSourceContext.java:161)
> 	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext$FlywayDatabasePreparer.<init>(DefaultFlywayDataSourceContext.java:170)
> 	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.lambda$reload$0(DefaultFlywayDataSourceContext.java:110)
> 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
> 	... 52 common frames omitted

As you can see from the `FlywayConfigSnapshot` it is trying to access a method that no longer exists!

Please could you verify?

I fixed it by migrating back to Flyway version 4.1.0: `runtime("org.flywaydb:flyway-core:4.1.0")`

**Comment by tomix26** [comment]
Hi Max, thanks for the info. We will fix it in the next release.

**Comment by maxkramerbcgdv** [comment]
@tomix26 would it be enough to simply update the Flyway version used in the build.gradle? If so, I'd be happy to make this change.

**Comment by tomix26** [comment]
@maxkramerbcgdv The new version has been released so you can try it.

But keep in mind that there is another issue related to compatibility with Spring Boot 2 + Hibernate + Postgres Driver and to resolve it, you'll need to add `spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true` property to your application configuration.

More information here:
https://github.com/spring-projects/spring-boot/issues/12007
https://hibernate.atlassian.net/browse/HHH-12368
