### ISSUE TITLE
Multiple databases problem

### ISSUE THREAD

**Issue by chikien276** [zonkyio/embedded-database-spring-test#64]
Currently I am following this tutorial https://www.baeldung.com/spring-data-jpa-multiple-databases  and your example repo to setting up my project with 2 data sources. But when I run the test it always produce this error no matter which bean name I provide
`Caused by: java.lang.ClassCastException: class io.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean$$EnhancerBySpringCGLIB$$d97cbff cannot be cast to class javax.sql.DataSource (io.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean$$EnhancerBySpringCGLIB$$d97cbff is in unnamed module of loader 'app'; javax.sql.DataSource is in module java.sql of loader 'platform')
`
Could you please take a look ?

**Comment by chikien276** [comment]
I've tried `@AutoConfigureEmbeddedDatabase(beanName = "userDataSource") and `@AutoConfigureEmbeddedDatabase(beanName = "userEntityManager") but there was no luck

**Comment by tomix26** [comment]
I think it is the same problem as here https://github.com/zonkyio/embedded-database-spring-test/issues/11. There is described how to work around the problem.

**Comment by tomix26** [comment]
I'll mention it in the readme.

**Comment by chikien276** [comment]
Thank you for making this project and also your response. This is my workaround and I've managed to make it works.
```
@Bean
    public FactoryBean<DataSource> userDataSource() {
        return new FactoryBean<DataSource>() {
            @Override
            public DataSource getObject() {
                return userDs();
            }

            @Override
            public Class<?> getObjectType() {
                return DataSource.class;
            }

            @Override
            public boolean isSingleton() {
                return true;
            }
        };
    }
   public DataSource userDs() {
        return DataSourceBuilder.create().build();
    }
```
