### ISSUE TITLE
Docker provider doesn't get loaded.

### ISSUE THREAD

**Issue by nezygis** [zonkyio/embedded-database-spring-test#75]
Hey, I am trying to use the docker provider for my tests and I have added test containers postgre dependency. After application context loads I can see that only zonky database provider is loaded. Is any additional configuration needed for that? I set provider globally in application.properties file zonky.test.database.provider=DOCKER

Thank you in advance.

**Comment by tomix26** [comment]
Can you please tell us what was the problem?

**Comment by nezygis** [comment]
I had excluded junit 4 as a dependency in gradle and that was causing the
issue. I tried to get it to work without it because I had junit 5 in the
project but couldnt.

**Comment by tomix26** [comment]
Ok, thanks for the information.
