### ISSUE TITLE
I couldn't run JUnit tests on gitlab-ci

### ISSUE THREAD

**Issue by rake-inc** [zonkyio/embedded-database-spring-test#77]
I trying to do CI using a standalone gitlab-ci runner container in a dedicated server. To run the tests I'm using zonky to create a postgis database service which is also containerized. It runs fine in my local machine. But while my Gitlab-ci runs the test it throws `Illegalstateexception` as it failed to load the application context. Anyone else experienced the same? 

Thanks in advance.

**Comment by tomix26** [comment]
Could you please attach your log? That will help in investigating the problem.

**Comment by nawrasNasser** [comment]
I also had a problem in gitlab-ci because the user who build the application should not be a root and the default user in gillab runner is a root. my solution was in .gitlab-ci.yml to create non-root user:
  script:
    - id -u userName &>/dev/null || adduser --disabled-password --gecos 'userName' userName
    - echo "userName:userpass" | chpasswd
    - su - userName -c "cd /builds/co/my-app; mvn clean package -q"

maybe the commands are not accurate but i hope i could help

**Comment by tomix26** [comment]
@nawrasNasser Thanks for the investigation, I'll mention it in the readme.

**Comment by fletchgqc** [comment]
The solution of creating a non-root user worked for me - thanks. But it's not really ideal, I had to install adduser and su on the docker image, I would prefer another solution.

Could somebody please explain what is behind this? Why do the tests need to run as a non-root user? Is there an alternative solution which allows them to run as root?

**Comment by tomix26** [comment]
It is a restriction of PostgreSQL database and it is described here: https://www.postgresql.org/docs/current/app-initdb.html
> initdb must be run as the user that will own the server process, because the server needs to have access to the files and directories that initdb creates. Since the server cannot be run as root, you must not run initdb as root either. (It will in fact refuse to do so.)

The only alternative is use of the [docker provider](https://github.com/zonkyio/embedded-database-spring-test#using-docker-provider) that runs the database in a docker container. The container is isolated from the system running on Gitlab workers, so it solves all issues related to the users and privileges.

**Comment by dirkbolte** [comment]
> I also had a problem in gitlab-ci because the user who builds the application should not be a root and the default user in gillab runner is a root. My solution was in .gitlab-ci.yml to create non-root user:
> 
> ```
>   script:
>     - id -u userName &>/dev/null || adduser --disabled-password --gecos 'userName' userName
>     - echo "userName:userpass" | chpasswd
>     - su - userName -c "cd /builds/co/my-app; mvn clean package -q"
> ```
> 
> maybe the commands are not accurate but i hope i was helpful

For making it work for me, I had to adapt it a bit:
The image that worked for me was one from Gradle - this one has a user created already + the `su` command is present (the openjdk images won't work out of the box).

The command should be adapted as well to not eradicate the environment and stay in the same directory (`su - gradle` -> `su -m gradle`)

So my job definition looks like this:

```yml
'server test':
    image: gradle:jdk14
    stage: test
    script:
        - su -m gradle -c "./gradlew check --no-daemon --no-build-cache --no-parallel --info"
```

If you use this, make sure that you wrap ALL calls to gradle in `su -m gradle -c` . When migrating to this approach, ensure that you clear all caches upfront as they are potentially created by a root user before.
