### ISSUE TITLE
Not reseting database after each test on a @SpringBootTest test

### ISSUE THREAD

**Issue by rrigoni** [zonkyio/embedded-database-spring-test#78]
This is my configuration:

`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Slf4j
@AutoConfigureEmbeddedDatabase
@AutoConfigureMockMvc
public abstract class AbstractIntegrationTest extends AbstractTestCase {`

I'm persisting some data on a method @BeforeEach  and the 1st test run just fine. 

When I run the entire test class, all tests are executed in sequence, second test always fails because of a duplicate key in the database. It sounds like a new database per test is not getting created. 

I think I should enable the @DataJpaTest, but it cannot be used at the same time with @SpringBootTest and the scope of my test is to test controller -> service -> persistence using the Embedded Postgres. 

Any idea?

**Comment by tomix26** [comment]
You have to place `@FlywayTest` annotation on your test class or test method. The `@FlywayTest` 
 annotation has set `invokeCleanDB` and `invokeMigrateDB` attributes to true by default, so it will refresh the database. Moreover, the embedded-database-spring-test library can optimize the database refresh, so this operation should be relatively fast and efficient. The database templates are used for this purpose.

In the future, I plan to extend the `@AutoConfigureEmbeddedDatabase` annotation by a refreshMode attribute (#21), so it will be possible to use it as follows: `@AutoConfigureEmbeddedDatabase(refreshMode = RefreshMode.AFTER_EACH_TEST_METHOD)`. It will also be possible to place this annotation on an abstract test class or use it in a composed annotation to apply this behavior to all tests.

**Comment by oeddyo** [comment]
Hi @tomix26 

I'm seeing this issue too. I have the following config
```

@SpringBootTest
@AutoConfigureEmbeddedDatabase
class AccountRepositoryTest {
  @Autowired
  private AccountRepository accountRepository;

  private final RandomEntityGenerator randomEntityGenerator =
      new RandomEntityGenerator(new Random());

  private List<Account> insertRandomAccounts(int num) {
    List<Account> randomAccounts = Lists.newArrayList();
    for (int i = 0; i < num; i++) {
      Account account = randomEntityGenerator.randomAccount();
      randomAccounts.add(
          accountRepository.save(account)
      );
    }
    return randomAccounts;
  }

  @FlywayTest
  @Test
  @DisplayName("correctly find one by email")
  public void findByEmailReturns() {
    List<Account> accounts = insertRandomAccounts(1);
    assertThat(accountRepository.findByEmail(accounts.get(0).getEmail()).get())
        .isEqualTo(accounts.get(0));
  }

```

Note for this I'm using `SpringBootTest` and add FlywayTest for each method. If I make a copy of this test, and run two test files in parallel, it fails (I simplified the test and pasted here, but I'm doing counting of how many items in db etc).

If I make this:
```

@DataJpaTest
@AutoConfigureEmbeddedDatabase
@FlywayTest
class AccountRepositoryTest {
```

instead, it works fine and can run in parallel without any issue. But by using DataJpaTest it doesn't allow me to load beans I need. Thus I really need to run with SpringBootTest but as seen in case 1, it seems to not cleaning db after each run.

Any ideas or pointers?
