### ISSUE TITLE
How to set username, password and port for embedded database?

### ISSUE THREAD

**Issue by padmalcom** [zonkyio/embedded-database-spring-test#83]
Hi, first of all: thanks for your effort to start this project!
I try to set username, password and port for the embedded database but I can't find any way to do this. Is it possible at all?

**Comment by tomix26** [comment]
Hey, why do you need it? The library should automatically create a preconfigured data source, so manual configuration should not be needed. All you have to do is inject the data source into your test class, as described in the documentation: https://github.com/zonkyio/embedded-database-spring-test#creating-a-new-empty-database-with-a-specified-bean-name

**Comment by tomix26** [comment]
No response, I'm closing the issue.

**Comment by bilak** [comment]
@tomix26 sorry for writing to closed issue. we are running our dockerized postgresql instances while working on DEV. But sometimes it's neede to run also som integration test. And both DEV and TEST are running port 5432. Can we somehow configure embedded db to use different port?
