### ISSUE TITLE
Support "max_connections" property for default Zonky provider

### ISSUE THREAD

**Issue by pixelstuermer** [zonkyio/embedded-database-spring-test#93]
Although the `zonky.test.database.postgres.server.properties.max_connections` property can be set within the configuration, it doesn't seem to affect the `ZonkyPostgresDatabaseProvider`. Within the default provider, the property is hardcoded to a constant.

```java
private static final int MAX_DATABASE_CONNECTIONS = 300;
```
And the `EmbeddedPostgres.Builder` only takes this constant for its configuration as well (instead of the configured property).

```java
public final void applyTo(EmbeddedPostgres.Builder builder) {
    // ...
    builder.setServerConfig("max_connections", String.valueOf(MAX_DATABASE_CONNECTIONS));
    // ...
}
```

Querying the `SHOW max_connections;` SQL against the running in-memory database therefore results in the following.

```
+-----------------+
| max_connections |
+-----------------+
| 300             |
+-----------------+
```

In contrast. the `DockerPostgresDatabaseProvider` for example, supports the configuration property and only sets the default if not configured.

```java
 private DatabaseInstance(DatabaseConfig config) {
    // ...
    serverProperties.putIfAbsent("max_connections", "300");
    // ...
}
```

**Comment by tomix26** [comment]
This restriction is because the builder does not allow to get the current value of the `max_connections` property. But you're right that this could be bypassed by calling the `SHOW max_connections` query. Nice idea, thanks.
